### ISSUE TITLE
Does not recognize underline (=) notation as heading 1.

### ISSUE THREAD

**Issue by crivetimihai** [timvink/mkdocs-enumerate-headings-plugin#11]
It does not recognize underline (=) notation as heading 1.

**Comment by timvink** [comment]
Hi @crivetimihai ,

Thanks for reporting. I'm having trouble reproducing this issue. Can you give a specific example?

**Comment by crivetimihai** [comment]
Hi Tim,

Thanks for the reply. I think the plugin is very cool - I love the idea. But I'm having issues getting it to work with different types of markdown notations. Example:

# Issue 1: support for underscore headings

The headings are only detected if you're using the `# Heading 1` style of markdown notation, but not the `Heading 1` with `============` below.

Is this using a markdown parser or regexp to detect headings?

Reproducing the issue:

requirements.txt
``` 
mkdocs
mkdocs-enumerate-headings-plugin
```

mkdocs.yml
```yaml
nav:
  - 'Introduction': 'index.md'

site_name: test

plugins:
    - search
    - enumerate-headings
```

docs/index.md 
```md
Heading 1 with underlines
=========

# Heading 1 with hash

Heading 2 with underline
---------

Test

Heading 2 with underline
---------

# Heading 2 with hash

Test

# Heading 3
```

Test
```bash
python -m venv .python37
source .python37/bin/activate
mkdocs serve
```

Output HTML:
```
Heading 1 with underlines
1. Heading 1 with hash
Heading 2 with underline
Test

Heading 2 with underline
2. Heading 2 with hash
qsadas

3. Heading 3
```

# Issue 2: Regexp breaks when there is no space after the `#`
```
#heading-break-regexp
AssertionError: Line '#heading-break-regexp' does not match regex
```

This can be fixed by adding a space: `# heading-break-regexp`

**Comment by timvink** [comment]
> I think the plugin is very cool - I love the idea. 

Thanks! I think this plugin is actually the coolest & most useful MkDocs plugin I've built -- but not the one that's picking up a lot of traction 🤷‍♂️ 

> I'm having issues getting it to work with different types of markdown notations
> Issue 1: support for underscore headings

Thanks for the clarification. I only now learned that there are two styles of markdown headings that `mkdocs` supports (through [python-markdown](https://python-markdown.github.io/reference/)): atx and setext (see [reference](https://daringfireball.net/projects/markdown/syntax#header)).

The setext implementation has all kinds of [specifics](https://github.github.com/gfm/#setext-headings) that I don't want to replicate. Perhaps I took the wrong approach with the first version of this plugin: I should have let [python-markdown](https://python-markdown.github.io/reference/) do the parsing for me and use the HTML to retrieve headings. Long story short: no support for setext style headings for now. Will try to include support in a next major version.

> Issue 2: Regexp breaks when there is no space after the #

Proper behaviour should be to ignore, not through an error, as it is not a valid heading. I will look into this, thanks!

**Comment by crivetimihai** [comment]
I really like the idea (enumerate headings). Form word templates to DITA and LaTeX templates - I use enumeration in all my documents. It even makes sense if you use `pdf-export` with mkdocs.

> Thanks! I think this plugin is actually the coolest & most useful MkDocs plugin I've built -- but not the one that's picking up a lot of traction man_shrugging

Haha, for sure, though I think `mkdocs-table-reader-plugin` comes close!!  I just realized you're the author for `git-authors` and `git-revision-date-localized` - which, along with `awesome-pages` makes mkdocs.. well.. awesome! Thanks for sharing :-).

From an implementation perspective, is there a way to tie into whatever mkdocs is doing and piggy back on their parser / extend some classes or something? Or is there some super secret Jinga technique you could be using? 

Thinking `python-markdown` is a better approach than regexp, for sure, but I'm still not clear on how this will behave when you have other plugins.
(just brainstorming..)

**Comment by flywire** [comment]
>  I think this plugin is actually the coolest & most useful MkDocs plugin I've built -- but not the one that's picking up a lot of traction 🤷‍♂️

I don't know about plugins but the [docs](https://www.mkdocs.org/) list [Third-Party-Extensions](https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions).

**Comment by timvink** [comment]
@crivetimihai I just released `v0.2` to address both issues. Thanks for the report, I wouldn't have found this better approach without it.

**Comment by flywire** [comment]
I will test some more but initially:
`ERROR   -  Error reading page 'index.md': Line '#include "my_dialog .h"' does not match regex`

Given second character is not a space I'd expect it to pass through.

**Comment by timvink** [comment]
I suspect you're still running `v0.2`, try:

```bash
pip install --upgrade --force-reinstall mkdocs-enumerate-headings-plugin
```

**Comment by flywire** [comment]
Hmm yes (Win10)

E:\...>pip3 install --upgrade --force-reinstall mkdocs-enumerate-headings-plugin
...
Successfully uninstalled mkdocs-enumerate-headings-plugin-0.2
Successfully installed Jinja2-2.11.2 Markdown-3.2.2 MarkupSafe-1.1.1 PyYAML-5.3.1 beautifulsoup4-4.9.1 click-7.1.2 future-0.18.2 importlib-metadata-1.6.1 joblib-0.15.1 livereload-2.6.2 lunr-0.5.8 mkdocs-1.1.2 **mkdocs-enumerate-headings-plugin-0.2** nltk-3.5 regex-2020.6.8 six-1.15.0 soupsieve-2.0.1 tornado-6.0.4 tqdm-4.46.1 zipp-3.1.0

**Comment by flywire** [comment]
Yes running v0.2 on Win10:
**input:**
~~~
• #include <QApplication>
#include "my_dialog .h"
Read the headers of, respectively, the Qt QApplication class
~~~
**output:**

![image](https://user-images.githubusercontent.com/11288701/84564843-3267dd00-ada8-11ea-9e48-c509446e8fd0.png)

**Comment by timvink** [comment]
Is that the output you expected? If `enumerate-headings` is messing up the output (and disabling it repairs it), then please open a new issue and also include your `mkdocs.yml` setup.

**Comment by flywire** [comment]
I understood  https://github.com/timvink/mkdocs-enumerate-headings-plugin/issues/11#issuecomment-634249098 that headings would not occur without a space following `#`:
> Issue 2: Regexp breaks when there is no space after the #

[`mkdocs.yml`](https://github.com/timvink/mkdocs-enumerate-headings-plugin/issues/13#issuecomment-643594016)

**Comment by timvink** [comment]
Yes, the error should not occur. The heading creation does occur. Note that this default behaviour of `MkDocs`. Your example `index.md`:

```markdown
• #include <QApplication>
#include "my_dialog .h"
Read the headers of, respectively, the Qt QApplication class
```

with `mkdocs.yml`:

```yml
site_name: test plugin
use_directory_urls: false

plugins:
    - search
```

Renders as:

![image](https://user-images.githubusercontent.com/5570380/84567209-7393c900-ad77-11ea-84f8-2c0ea590b9ab.png)

And with `enumerate-headings` enabled, it properly adds the enumeration:

![image](https://user-images.githubusercontent.com/5570380/84567228-945c1e80-ad77-11ea-9f65-9aa8c25ad7be.png)

**Comment by crivetimihai** [comment]
Hi, probably another thing to consider: not all pages have a Heading 1. For example, you can leave that out, and Heading 1 automatically becomes the page name.

If that's the case, then this will return:
```
    return "#" + self.heading.get("id")
TypeError: can only concatenate str (not "NoneType") to str
```

To make it fully compatible with mkdocs, Heading 1 should also be derived from the page title if there is none present in the document.

**Comment by timvink** [comment]
Ah! I have unit tests for pages without headings, and unit tests for compatiblity with `awesome-pages`, but not this case. I opened #18 and will probably look into it next weekend.
