### ISSUE TITLE
Problems Rendering Characters

### ISSUE THREAD

**Issue by flywire** [timvink/mkdocs-enumerate-headings-plugin#12]
Will not render the second character in the following line correctly:
Tèst this

> Each character is represented by a single byte, except for the UTF-8 è character, which is c3a8, so it is represented by 2 bytes.

**Comment by timvink** [comment]
Probably this weekend. Almost there, but of course some unit tests fail for windows..

**Comment by timvink** [comment]
@flywire let me know if the newly released `v.2` addresses this problem

**Comment by flywire** [comment]
I will test some more but initially:
`ERROR   -  Error reading page 'index.md': Line '#include "my_dialog .h"' does not match regex`

Given second character is not a space I'd expect it to pass through.

**Comment by flywire** [comment]
Fixed in https://github.com/timvink/mkdocs-enumerate-headings-plugin/releases/tag/v0.2
