### ISSUE TITLE
Contents Only Displays Level 2 and Below to Last Level One Heading in File

### ISSUE THREAD

**Issue by flywire** [timvink/mkdocs-enumerate-headings-plugin#13]
**Sample_input_file.md**
```
mkdocs-enumerate-headings-plugin

**test file**

# First Level One Heading

text

## First Level Two Heading

### First Level Three Heading

## Second Level Two Heading

more text

# Second Level One Heading

yet more text

## First Sub-heading

still more text
```

**Output**

**Table of contents**
1.1 First Level Two Heading
  1.1.1 First Level Three Heading
1.2 Second Level Two Heading

---

**Expected Output**

**Table of contents**
1 First Level One Heading
1.1 First Level Two Heading
  1.1.1 First Level Three Heading
1.2 Second Level Two Heading
2 Second Level One Heading
2.1 First Sub-heading

**Comment by timvink** [comment]
@flywire let me know if the newly released `v.2` addresses this problem

**Comment by flywire** [comment]
~~~
test file

1. First Level One Heading
text

1.1 First Level Two Heading
1.1.1 First Level Three Heading
1.2 Second Level Two Heading
more text

2. Second Level One Heading
yet more text

2.1 First Sub-heading
still more text
~~~

~~~
Table of contents
1.1 First Level Two Heading
1.1.1 First Level Three Heading
1.2 Second Level Two Heading
~~~

I expect `2.1 First Sub-heading` to be displayed

**Comment by timvink** [comment]
Try reinstalling:

```bash
pip install --upgrade --force-reinstall mkdocs-enumerate-headings-plugin
```

The heading renders correctly:

![image](https://user-images.githubusercontent.com/5570380/84563589-fb200e80-ad5c-11ea-926f-fd854438b5ee.png)

**Comment by flywire** [comment]
Reinstalled and running V0.2

~~~
test file

1. First Level One Heading
text

1.1 First Level Two Heading
1.1.1 First Level Three Heading
1.2 Second Level Two Heading
more text

2. Second Level One Heading
yet more text

2.1 First Sub-heading
still more text
~~~

~~~
Table of contents
First Level Two Heading
  First Level Three Heading
Second Level Two Heading
~~~

I expect Table of contents to display numbers. 

**mkdocs.yml**
~~~
site_name: Tutorial how to use Travis CI with C++
repo_url: https://github.com/flywire/travis_cpp_tutorial/
edit_uri: edit/Development/docs/

theme:
    name: material
    
markdown_extensions:
    - toc:
        permalink:
    - admonition
    - def_list
    - nl2br
    - pymdownx.magiclink
    - pymdownx.snippets
    - attr_list
    - markdown_blockdiag:
        format: svg
        
extra_css:
    - css/extra.css
    
plugins:
    - search
    - enumerate-headings
  
nav:
    - Tutorial: testfile.md
~~~

**Comment by timvink** [comment]
So I understand it works correctly for you now.

> Should probably support turning level one heading on in TOC too.

I don't plan to support showing the enumeration in the table of contents as well. If you would like to work on a PR, I'd be happy to provide some guidance though. We could open a new issue to discuss intended behaviour for TOC.
