### ISSUE TITLE
Compatiblity with awesome-pages plugin Page names

### ISSUE THREAD

**Issue by timvink** [timvink/mkdocs-enumerate-headings-plugin#18]
@crivetimihai reports https://github.com/timvink/mkdocs-enumerate-headings-plugin/issues/11#issuecomment-643745201 a bug when using `awesome-pages` page names.

Todo:

- [ ] write unit test to reproduce problem
- [ ] fix :)

**Comment by timvink** [comment]
@crivetimihai I spent some time on this but cannot manage to reproduce the error. 

I realize the page title can be specified in 4 ways (see [here](https://www.mkdocs.org/user-guide/writing-your-docs/#meta-data)). They only effect the title in the navigation, not the `h1` title on the top of the page.

Perhaps you can help with a minimal example to reproduce your error?

**Comment by crivetimihai** [comment]
I've reproduced the error here, with a minimal `mkdocs.yaml` example: https://github.com/crivetimihai/enumerate-headings-unit-test

The error occurs on empty files or files that are missing a Heading 1. I've attached two example `mkdocs.yml` and `mkdocs-nav.yaml` that break with `enumerate-headings`.

**Comment by timvink** [comment]
Thanks for all the effort in reproducing this! Super helpful and I managed to find the bug very quickly.

My unit test suite was using the base mkdocs theme, yours uses `mkdocs-material`. I did not realize that some themes insert missing heading 1's. 

Using your unit test I found multiple problems to fix:

1) I assumed all page headings have a `id` attribute (for anchor links, used to enumerate the table of contents) --> Easy to fix with an if else
2) Enumeration between pages does increment properly. I used the `on_nav` event where I prebuild the pages, to find out how many heading 1's they have. The theme will later add h1, so this approach does not always work. --> Instead, I will now assume all pages always have at least one heading 1, even if they are empty. Seems like a very reasonable assumption.

Both are addressed in #19 , where I also updated the documentation a bit and added the unit tests.

**Comment by timvink** [comment]
And I released `v0.4`: https://github.com/timvink/mkdocs-enumerate-headings-plugin/releases/tag/v0.4

**Comment by crivetimihai** [comment]
You *rock*. I've turned it on for a few of my repositories and now it works! This is brilliant, thank you!

One thing - it looks like it numbers everything across the entire mkdocs nav structure, so by the end you'll end up with section 498.17 or something like that. Is this configurable (ex: chapters per nav 'parts') or normal behavior?

**Comment by timvink** [comment]
Whoop whoop, good to hear !

And wow almost 500 pages, that's a large site. It's normal behavior because counter is per page. Doing that per nav section should be doable, might be complicated due to edge cases with other plugins interacting with the nav. 

Can you open a new issue for it? We can see if more users want that functionality and I can consider it for a future release.
