### ISSUE TITLE
Compatibility with awesome-pages

### ISSUE THREAD

**Issue by morido** [timvink/mkdocs-enumerate-headings-plugin#25]
Hi,

the [README.md](https://github.com/timvink/mkdocs-enumerate-headings-plugin/blob/master/README.md) states this plugin is compatible with [awesome-pages](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin).

I feel this is only true if `enumerate-headings` is loaded **after** `awesome-pages` in `mkdocs.yml`, i.e. like so:

```YAML
plugins:
  - search
  - awesome-pages
  - enumerate-headings # ensure this comes after awesome-pages
```

If you fail to do this directives in `awesome-pages`'s `.pages` such as hiding a directory or sorting navigation will not be respected by  `enumerate-headings`.

Provided my observation is correct can this be added to the [README.md](https://github.com/timvink/mkdocs-enumerate-headings-plugin/blob/master/README.md), please?

**Comment by timvink** [comment]
Hi @morido , 

That's correct, the ordering matters. I added a WARNING when the ordering is wrong. F.e.:

```shell
git clone https://github.com/timvink/mkdocs-enumerate-headings-plugin
cd mkdocs-enumerate-headings-plugin
mkdocs serve -f tests/fixtures/projects/awesome_pages/mkdocs_enum_first.yml 
# INFO    -  Building documentation... 
# WARNING -  [enumerate-headings-plugin] enumerate-headings should be defined after the awesome-pages plugin in your # mkdocs.yml file
# INFO    -  Cleaning site directory 
# INFO    -  Documentation built in 0.22 seconds 
# [I 210322 15:28:27 server:335] Serving on http://127.0.0.1:8000
```

Did you see the WARNING in your case? Would throwing an error be more appropriate?

**Comment by timvink** [comment]
Hi @morido , can you follow up on this one?

I'm inclined to change the warning to an error, seems more user friendly.
