### ISSUE TITLE
h1 Numbering options?

### ISSUE THREAD

**Issue by aforsythe** [timvink/mkdocs-enumerate-headings-plugin#31]
This plugin is very close to what I'm looking for. 

Is there a way to have h1 not numbered and start at h2?  Use case here is if h1 on a page is a page title, not a section.

Or, is there a way to make h1 show up in the toc?
Right now it seems only h2 downward show up in the toc and only for those under the first h1 if there are multiple h1 on a page.

**Comment by timvink** [comment]
Interesting. I'd might open to adding it, but it need some design. 

Let's consider this site with `page_one.md` and `page_two.md`:

```yaml
# page one

## heading

### subheading

## heading

# another heading


```

```yaml
# page two

## heading

### subheading

## heading
```

What would be the correct enumeration for those if we ignore the h1 headings? Note that by default, this plugin enumerates chapters across pages, and that some users put multiple heading 1s in a page.

Btw, these are the [toc options](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/?h=toc#table-of-contents). The ToC shows th
e contents in a page, if you want the page title to keep showing, you could consider sticky tabs navigation feature in mkdocs-material.

**Comment by timvink** [comment]
For reference this is the current enumeration with default settings:

```yaml
# 1. page one

## 1.1 heading

### 1.1.1 subheading

## 1.2 heading

# 2. another heading
```

```yaml
# 3. page two

## 3.2 heading

### 3.2.1 subheading

## 3.3 heading
```

**Comment by aforsythe** [comment]
My use case is that h1. is really the title of the page / document (each page is a stand alone document in my instance).  It's a little weird to have all sections on the page have the same root number since there's only one h1. on the page.  I really do need section numbers because my documents say things like "See section 4.2 ... It's great that you have so many options associated with the plugin, particularly the option to ignore certain pages.  Right now I'm using some CSS to do the section numbering, but that applies to all pages including things like my glossary page.

**Comment by timvink** [comment]
> It's a little weird to have all sections on the page have the same root number since there's only one h1

Some users have a use case for multiple h1's on a single page, and that should be supported also.

Gave it some thought, and there are going to be too many edge cases if I try to implement it. That also means it would take a considerable amount of time. I don't use this plugin anymore (I use [print-site](https://github.com/timvink/mkdocs-print-site-plugin) instead), so I won't spend time to implement big new features.

I would recommend trying to find a way to add a CSS class to a page, via front-matter or a mkdocs plugin. https://python-markdown.github.io/extensions/attr_list/ might be a good start.

I'm open for PRs, but if you're not up for implementing this one, I suggest you close the issue.

**Comment by aforsythe** [comment]
I totally understand ... I appreciate the consideration.  I'll look into a CSS based solution.

**Comment by ewels** [comment]
I'm a bit late to the party, but in case it's useful for any future googlers this is the custom CSS I used to only show enumeration on the heading levels I wanted (`h2` and `h3` only in my case):

```css
 .enumerate-headings-plugin {
     display: none;
 }
 h2 .enumerate-headings-plugin,
 h3 .enumerate-headings-plugin {
     display: inline;
 }
```

This doesn't change the numbering system though, only hides certain numbers. So everything would still be prefixed `1.` in the case described above.

**Comment by CrysK** [comment]
I am also looking for a way to not number h1.

> [...] to only show enumeration on the heading levels I wanted

the solution is a start, but in no way good.
The heading h1 is not numbered (correctly). But from h2 is numbered according to the scheme "h1.h2.etc", so for example "3.2" and not only (!) "2".

Is there a (css) way to remove the h1 numbering from the other headings (h2-h6) as well?

**Comment by CrysK** [comment]
Thanks @ewels!

I don't know JS well, but with this I have achieved my desired result:

in mkdocs.yml
```
plugins:
    - search
    - enumerate-headings:
extra_javascript:
    - file.js
```


Content of file.js
```// Remove h1 enumeration
var enumBody = document.getElementsByClassName("enumerate-headings-plugin enumerate-heading-plugin");
for (var i = 0; i < enumBody.length; i++) {
	enumBody[i].innerHTML = enumBody[i].innerHTML.substring(enumBody[i].innerHTML.indexOf('.')+1);
}
var enumNavi = document.getElementsByClassName("md-nav__link");
for (var i = 0; i < enumNavi.length; i++) {
	enumNavi[i].innerHTML = enumNavi[i].innerHTML.substring(enumNavi[i].innerHTML.indexOf('.')+1);
}
```

**Comment by timvink** [comment]
Thanks for sharing your solution! 

Indeed my time is limited now, especially with two kids. So only maintaining plugins I actually use myself :)

**Comment by lambdamusic** [comment]
Thanks @CrysK - works just perfect!
